commit 31c0e523c2f0e1654b2fe893a9620dfa30b56698
Author: Jan-Piet Mens <jpmens@gmail.com>
Date:   Wed Aug 1 15:30:16 2012 +0200

    Fix exeptions, replace 'as' by ',' as reported on IRC for Python 2.4.3 on Centos5

diff --git a/library/get_url b/library/get_url
index bb125d9494..5f166629c9 100755
--- a/library/get_url
+++ b/library/get_url
@@ -77,11 +77,11 @@ def url_do_get(module, url, dest):
         r = urllib2.urlopen(request)
         info.update(r.info())
         info.update(dict(msg="OK (%s bytes)" % r.headers.get('Content-Length', 'unknown'), status=200))
-    except urllib2.HTTPError as e:
+    except urllib2.HTTPError, e:
         # Must not fail_json() here so caller can handle HTTP 304 unmodified
         info.update(dict(msg=str(e), status=e.code))
         return r, info
-    except urllib2.URLError as e:
+    except urllib2.URLError, e:
         code = getattr(e, 'code', -1)
         module.fail_json(msg="Request failed: %s" % str(e), status_code=code)
 
