commit b8907ff09efeb8601fdfcd4d2e91fc562e92da58
Author: Will Thames <will@thames.id.au>
Date:   Tue Aug 28 12:51:26 2018 +1000

    k8s_facts should not throw exceptions when not found (#44429)
    
    Handle the case where a resource is not found by catching
    the exception and returning an empty result set.

diff --git a/lib/ansible/module_utils/k8s/common.py b/lib/ansible/module_utils/k8s/common.py
index edb8fa3aab..95839daabf 100644
--- a/lib/ansible/module_utils/k8s/common.py
+++ b/lib/ansible/module_utils/k8s/common.py
@@ -205,10 +205,14 @@ class K8sAnsibleMixin(object):
 
     def kubernetes_facts(self, kind, api_version, name=None, namespace=None, label_selectors=None, field_selectors=None):
         resource = self.find_resource(kind, api_version)
-        result = resource.get(name=name,
-                              namespace=namespace,
-                              label_selector=','.join(label_selectors),
-                              field_selector=','.join(field_selectors)).to_dict()
+        try:
+            result = resource.get(name=name,
+                                  namespace=namespace,
+                                  label_selector=','.join(label_selectors),
+                                  field_selector=','.join(field_selectors)).to_dict()
+        except openshift.dynamic.exceptions.NotFoundError:
+            return dict(items=[])
+
         if 'items' in result:
             return result
         else:
