commit db2d5b09eff918e981c9e10787a5f2c500d1784f
Author: Felix Fontein <felix@fontein.de>
Date:   Sun Mar 1 04:47:44 2020 +0100

    ldap_attr: fix small bug (using wrong variable) (#67887)
    
    Changed self.name to name in ldap_attr module

diff --git a/lib/ansible/modules/net_tools/ldap/ldap_attrs.py b/lib/ansible/modules/net_tools/ldap/ldap_attrs.py
index 61e110f64c..2be830cfb0 100644
--- a/lib/ansible/modules/net_tools/ldap/ldap_attrs.py
+++ b/lib/ansible/modules/net_tools/ldap/ldap_attrs.py
@@ -250,7 +250,7 @@ class LdapAttrs(LdapGeneric):
                 results = self.connection.search_s(
                     self.dn, ldap.SCOPE_BASE, attrlist=[name])
             except ldap.LDAPError as e:
-                self.fail("Cannot search for attribute %s" % self.name, e)
+                self.fail("Cannot search for attribute %s" % name, e)
 
             current = results[0][1].get(name, [])
 
