commit 6723566d85d53af3a488fecec7447c9604873195
Author: David Cramer <dcramer@gmail.com>
Date:   Wed Sep 15 18:19:54 2010 -0700

    We cannot pass extra to logging.exception

diff --git a/sentry/client/base.py b/sentry/client/base.py
index 677fb9ed6f..34d8cc52eb 100644
--- a/sentry/client/base.py
+++ b/sentry/client/base.py
@@ -52,10 +52,10 @@ class SentryClient(object):
                 try:
                     response = urllib2.urlopen(req, None, settings.REMOTE_TIMEOUT).read()
                 except urllib2.URLError, e:
-                    logger.exception('Unable to reach Sentry log server: %s' % (e,), extra={'remote_url': url})
+                    logger.error('Unable to reach Sentry log server: %s' % (e,), extra={'exc_info': sys.exc_info(), 'remote_url': url})
                     logger.log(kwargs.pop('level', None) or logging.ERROR, kwargs.pop('message', None))
                 except urllib2.HTTPError, e:
-                    logger.exception('Unable to reach Sentry log server: %s' % (e,), extra={'body': e.read(), 'remote_url': url})
+                    logger.error('Unable to reach Sentry log server: %s' % (e,), extra={'exc_info': sys.exc_info(), 'body': e.read(), 'remote_url': url})
                     logger.log(kwargs.pop('level', None) or logging.ERROR, kwargs.pop('message', None))
         else:
             from sentry.models import GroupedMessage
