commit b71c2447461537a1f4e32f11c087e05d7ef417da
Author: David Cramer <dcramer@gmail.com>
Date:   Thu Apr 4 10:58:05 2013 -0700

    Correct bug with second update attempt in create_or_update

diff --git a/src/sentry/utils/models.py b/src/sentry/utils/models.py
index 93afa18a4a..0c4c515c10 100644
--- a/src/sentry/utils/models.py
+++ b/src/sentry/utils/models.py
@@ -121,14 +121,15 @@ def create_or_update(model, using=None, **kwargs):
     if affected:
         return affected, False
 
+    create_kwargs = kwargs.copy()
     inst = objects.model()
     for k, v in defaults.iteritems():
         if isinstance(v, ExpressionNode):
-            kwargs[k] = resolve_expression_node(inst, v)
+            create_kwargs[k] = resolve_expression_node(inst, v)
         else:
-            kwargs[k] = v
+            create_kwargs[k] = v
     try:
-        return objects.create(**kwargs), True
+        return objects.create(**create_kwargs), True
     except IntegrityError:
         transaction.rollback_unless_managed(using=using)
         affected = objects.filter(**kwargs).update(**defaults)
